/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [ASMENSKODAS]
      ,[VARDAS]
      ,[PAVARDE]
      ,[DIRBANUO]
      ,[GIMIMOMETAI]
      ,[PAREIGOS]
      ,[SKYRIUS_PAVADINIMAS]
      ,[PROJEKTAS_ID]
  FROM [AdventureWorksDW2019].[dbo].[DARBUOTOJAS]
  SELECT * FROM DARBUOTOJAS;
  SELECT ASMENSKODAS FROM DARBUOTOJAS;
  SELECT VARDAS,PAVARDE,PAREIGOS FROM DARBUOTOJAS;
  SELECT DISTINCT SKYRIUS_PAVADINIMAS FROM DARBUOTOJAS;
SELECT SKYRIUS_PAVADINIMAS
FROM DARBUOTOJAS
WHERE SKYRIUS_PAVADINIMAS = 'C#';
SELECT VARDAS,PAREIGOS
FROM DARBUOTOJAS
WHERE VARDAS = 'Giedrius';
SELECT * FROM DARBUOTOJAS WHERE GIMIMOMETAI = '1986-09-19';
SELECT VARDAS,PAVARDE
FROM DARBUOTOJAS
WHERE PAVARDE = 'Sabutis';
SELECT VARDAS,PAVARDE,SKYRIUS_PAVADINIMAS 
FROM DARBUOTOJAS
WHERE SKYRIUS_PAVADINIMAS = 'Java';
SELECT VARDAS FROM DARBUOTOJAS WHERE VARDAS = 'Vardenis';
INSERT INTO DARBUOTOJAS(ASMENSKODAS,VARDAS,PAVARDE,DIRBANUO,GIMIMOMETAI) VALUES (39111110405,'Traidenis','Travardenis','2010-10-1','1990-01-01');
SELECT * FROM DARBUOTOJAS WHERE VARDAS = 'Traidenis';
INSERT INTO DARBUOTOJAS([PAREIGOS],[SKYRIUS_PAVADINIMAS],[PROJEKTAS_ID]) VALUES ('testuotojas','C#','2');
UPDATE DARBUOTOJAS SET [PAREIGOS]='testuotojas',[SKYRIUS_PAVADINIMAS]='C#',[PROJEKTAS_ID]=2 WHERE VARDAS = 'Traidenis';
SELECT * FROM DARBUOTOJAS WHERE VARDAS = 'Traidenis';
DELETE FROM [DARBUOTOJAS] WHERE ASMENSKODAS = 39111110405;
INSERT INTO DARBUOTOJAS([ASMENSKODAS],[PAVARDE],[PAREIGOS]) VALUES (38911110204,'Antanaitis','programuotojas'), (38911110205,'Antanaitis','programuotojas');
UPDATE DARBUOTOJAS SET [PAREIGOS]='testuotojas' WHERE VARDAS = 'Antanaitis';
SELECT @@ROWCOUNT * FROM DARBUOTOJAS WHERE PAREIGOS = 'testuotojas';
