/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [ASMENSKODAS]
      ,[VARDAS]
      ,[PAVARDE]
      ,[DIRBANUO]
      ,[GIMIMOMETAI]
      ,[PAREIGOS]
      ,[SKYRIUS_PAVADINIMAS]
      ,[PROJEKTAS_ID]
  FROM [AdventureWorksDW2019].[dbo].[DARBUOTOJAS]
  SELECT [ASMENSKODAS],[VARDAS],[PAVARDE] FROM [AdventureWorksDW2019].[dbo].[DARBUOTOJAS] WHERE [GIMIMOMETAI] = '1988-07-20';
  SELECT [DIRBANUO],[GIMIMOMETAI] FROM [AdventureWorksDW2019].[dbo].[DARBUOTOJAS] 
  WHERE [GIMIMOMETAI] <= '1988-07-29';
  SELECT * FROM [AdventureWorksDW2019].[dbo].[DARBUOTOJAS] 
  WHERE [DIRBANUO] <= '2012-11-11' AND [DIRBANUO] >= '2009-10-30';
  SELECT [VARDAS],[PROJEKTAS_ID],[ASMENSKODAS] FROM [AdventureWorksDW2019].[dbo].[DARBUOTOJAS] 
  WHERE [PROJEKTAS_ID] IN (2, 3);
  SELECT VARDAS, PAVARDE, ASMENSKODAS FROM DARBUOTOJAS WHERE PAVARDE LIKE '%e';
  SELECT * FROM DARBUOTOJAS WHERE GIMIMOMETAI LIKE '%12';
  SELECT PAREIGOS FROM DARBUOTOJAS WHERE PAREIGOS LIKE '____u%';
  SELECT * FROM DARBUOTOJAS WHERE SKYRIUS_PAVADINIMAS is NULL;










--  SELECT coulmn, group_function
--FROM table
--[WHERE condition]
--[GROUP BY list_to_group]
--[HAVING group_condition]
--[ORDER BY sorting_condition]

--SELECT Job, Sum(Sal) TotalSum FROM EMP 
--WHERE Job NOT LIKE ‘SALES%’
--GROUP BY Job 
--HAVING Sum(Sal) > 300 
--ORDER BY Sum(Sal)

